### ISSUE TITLE
Call stack unsubscribe with not subscriptions

### ISSUE THREAD

**Issue by DJWassink** [danielstjules/node-internal-pubsub#1]
I don't know if this can be seen as a bug (because there is a really easy way to work around it) but if you unsubscribe without passing any parameters and the subsriber doesn't has any subscriptions it will crass with the following error:

```
Maximum call stack size exceeded
```

I remember seeing somewhere that it crashed somewhere within a args.forEach() loop. This "bug" however is easily fixed by first checking the _count attribute of the subscriber but I am not sure if this is the right way to do this, hence this post.

**Comment by danielstjules** [comment]
Thanks for bringing this to my attention! It's been fixed in https://github.com/danielstjules/node-internal-pubsub/commit/348679b2b6ea353613e6563dfc75d1f0d924ba5b and I've released/tagged a new patch version of the library. 

Using _count wouldn't have been reliable, unfortunately, because of the following scenario:

```
var sub = require('node-internal-pubsub').createSubscriber();
sub.psubscribe(/pattern/);
sub.unsubscribe();
```

In this case, since _count would be 1, but there's no regular subscriptions (only pattern ones), the recursion would still blow the stack.

**Comment by DJWassink** [comment]
Awesome thanks for the quick fix! You are right about the patterns, I didn't had any use case to use a pattern subscription yet, so I didn't run into any problems with those yet. But I'm glad it is fixed if it's going to be used sometime soon. 

Just a little questions which is completely off-topic. Is there some easy way to see how many subscribers are subscribed to a certain channel? Currently I am placing all the sub's their subscriptions in a array and calculating it that way. However that is a difficult way of calculating it.

**Comment by danielstjules** [comment]
Not sure if this is what you're doing already, but it's likely the least "hacky" solution. That is, just listening for the subscribe/unsubscribe events.

``` javascript
var pubsub = require('node-internal-pubsub');
var channelCounts = {};

// Function for setting up the tracking
var installCountListeners = function(sub) {
  sub.on('subscribe', function(channel) {
    if (!channelCounts[channel]) {
      channelCounts[channel] = 0;
    }

    channelCounts[channel]++;
  });

  sub.on('unsubscribe', function(channel) {
    if (!channelCounts[channel]) return;

    channelCounts[channel]--;
  });
};

// Create subscribers, install listener, and
// susbcribe/unsubscribe, emulating some
// potential behaviour
var i, sub, channel;
for (i = 0; i < 10; i++) {
  sub = pubsub.createSubscriber();
  installCountListeners(sub);

  channel = (i % 2 === 0) ? 'channel1' : 'channel2';
  sub.subscribe(channel);

  if (i % 4 === 0) {
    sub.unsubscribe(channel);
  }
}

console.log(channelCounts);
// => { channel1: 2, channel2: 5 }
```

**Comment by DJWassink** [comment]
I was doing something similar but then listening in the Objects (made a few objects who simulate basic OO classes) for a subscription/removal. But the way you described it is way way cleaner. 

Thanks a ton for this example!

**Comment by danielstjules** [comment]
No problem, happy to help. :)
