### ISSUE TITLE
Benchmark update

### ISSUE THREAD

**Issue by jrots** [danielstjules/node-internal-pubsub#2]
Looks like a nice library - was just wondering as it's 3 years ago since the last commit, 
if benchmarks are still the same or if there is no support for this in ioredis/ node_redis itself?
Had a quick look to ioredis and node_redis projects source, 
but think it still heavily relies on creating separate clients per subscriber.  https://github.com/socketio/socket.io-redis semi does a bit the same, but it couples this to "chat rooms".  Just want to make a good choice when using this library in production environment. Thx!

**Comment by danielstjules** [comment]
I'd still multiplex if I were you, be it with this library or something else :) Always good to reduce IO. I use this same technique in other languages and projects.
